# Generated by Django 5.2.8 on 2026-01-05 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_occurred', models.DateTimeField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('physical', 'Körperlich'), ('psychological', 'Psychisch'), ('sexual', 'Sexuell'), ('financial', 'Finanziell'), ('other', 'Andere')], max_length=30)),
                ('severity', models.PositiveSmallIntegerField(default=1)),
                ('victim_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('victim_gender', models.CharField(choices=[('female', 'weiblich'), ('male', 'männlich'), ('other', 'divers'), ('unknown', 'unbekannt')], default='unknown', max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='open', max_length=30)),
                ('anonymized', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_occurred'],
            },
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
