# Generated by Django 5.2.8 on 2026-02-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_statspreset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
