from api.database.models import DataSet

# Fall 1
DataSet.objects.create(
    data_record="Fall",
    version=1,
    values={
        "alias": "Alex M.",
        "rolle": "Betroffene:r",
        "alter": 28,
        "geschlechts_identitaet": "trans weiblich",
        "sexualitaet": "lesbisch",
        "wohnort": "Stadt Leipzig",
        "staatsangehoerigkeit": "deutsch",
        "berufssituation": "berufstätig",
        "schwerbehinderung": False,
        "beratungsstelle": "Stadt Leipzig",
        "anzahl_beratungen": 3,
        "depression": True,
        "angststoerung": True,
        "ptbs": False,
        "anderes": False,
        "burn_out": False,
        "schlafstoerung": True,
        "sucht": False,
        "kommunikationsschwierigkeiten": False,
        "vernachlaessigung_alltäglicher_dinge": False,
        "schmerzen": False,
        "laehmungen": False,
        "krankheit": False,
        "finanzielle_folgen": True,
        "arbeits_einschraenkung": True,
        "verlust_arbeit": False,
        "soziale_isolation": True,
        "suizidalität": False,
        "begleitungen_gesamt": 2,
        "begleitungen_gerichte": 1,
        "begleitungen_polizei": 1,
        "begleitungen_rechtsanwaelte": 0,
        "begleitungen_aerzte": 0,
        "begleitungen_rechtsmedizin": 0,
        "begleitungen_jugendamt": 0,
        "begleitungen_sozialamt": 0,
        "begleitungen_jobcenter": 0,
        "begleitungen_beratungstellen": 0,
        "begleitungen_schutzeinrichtungen": 0,
        "begleitungen_schutzeinrichtungen_spezialisiert": 0,
        "begleitungen_interventionsstellen": 0,
        "verweise_gesamt": 1,
        "verweise_gerichte": 0,
        "verweise_polizei": 0,
        "verweise_rechtsanwaelte": 1,
        "verweise_aerzte": 0,
        "verweise_rechtsmedizin": 0,
        "verweise_jugendamt": 0,
        "verweise_sozialamt": 0,
        "verweise_jobcenter": 0,
        "verweise_beratungstellen": 0,
        "verweise_schutzeinrichtungen": 0,
        "verweise_schutzeinrichtungen_spezialisiert": 0,
        "verweise_interventionsstellen": 0,
        "quelle": "Internet",
        "dolmetsch_zeit": 0
    }
)

# Fall 2
DataSet.objects.create(
    data_record="Fall",
    version=1,
    values={
        "alias": "Sam K.",
        "rolle": "Fachkraft",
        "alter": 42,
        "geschlechts_identitaet": "divers",
        "sexualitaet": "bisexuell",
        "wohnort": "Landkreis Leipzig",
        "staatsangehoerigkeit": "deutsch",
        "berufssituation": "studierend",
        "schwerbehinderung": True,
        "schwerbehinderung_form": "körperlich",
        "schwerbehinderung_grad": "50",
        "beratungsstelle": "Landkreis Leipzig",
        "anzahl_beratungen": 5,
        "depression": False,
        "angststoerung": False,
        "ptbs": True,
        "anderes": True,
        "burn_out": True,
        "schlafstoerung": True,
        "sucht": False,
        "kommunikationsschwierigkeiten": True,
        "vernachlaessigung_alltäglicher_dinge": False,
        "schmerzen": True,
        "laehmungen": False,
        "krankheit": False,
        "finanzielle_folgen": False,
        "arbeits_einschraenkung": False,
        "verlust_arbeit": False,
        "soziale_isolation": False,
        "suizidalität": False,
        "begleitungen_gesamt": 4,
        "begleitungen_gerichte": 0,
        "begleitungen_polizei": 2,
        "begleitungen_rechtsanwaelte": 1,
        "begleitungen_aerzte": 1,
        "begleitungen_rechtsmedizin": 0,
        "begleitungen_jugendamt": 0,
        "begleitungen_sozialamt": 0,
        "begleitungen_jobcenter": 0,
        "begleitungen_beratungstellen": 0,
        "begleitungen_schutzeinrichtungen": 0,
        "begleitungen_schutzeinrichtungen_spezialisiert": 0,
        "begleitungen_interventionsstellen": 0,
        "verweise_gesamt": 3,
        "verweise_gerichte": 0,
        "verweise_polizei": 0,
        "verweise_rechtsanwaelte": 0,
        "verweise_aerzte": 2,
        "verweise_rechtsmedizin": 1,
        "verweise_jugendamt": 0,
        "verweise_sozialamt": 0,
        "verweise_jobcenter": 0,
        "verweise_beratungstellen": 0,
        "verweise_schutzeinrichtungen": 0,
        "verweise_schutzeinrichtungen_spezialisiert": 0,
        "verweise_interventionsstellen": 0,
        "quelle": "Beratungsstellen",
        "dolmetsch_zeit": 0
    }
)

# Fall 3
DataSet.objects.create(
    data_record="Fall",
    version=1,
    values={
        "alias": "Jamie R.",
        "rolle": "Angehörige:r",
        "alter": 19,
        "geschlechts_identitaet": "trans nicht binär",
        "sexualitaet": "asexuell",
        "wohnort": "Landkreis Nordsachsen",
        "staatsangehoerigkeit": "polnisch",
        "berufssituation": "Azubi",
        "schwerbehinderung": False,
        "beratungsstelle": "Landkreis Nordsachsen",
        "anzahl_beratungen": 1,
        "depression": True,
        "angststoerung": True,
        "ptbs": True,
        "anderes": False,
        "burn_out": False,
        "schlafstoerung": True,
        "sucht": True,
        "kommunikationsschwierigkeiten": True,
        "vernachlaessigung_alltäglicher_dinge": True,
        "schmerzen": False,
        "laehmungen": False,
        "krankheit": False,
        "finanzielle_folgen": True,
        "arbeits_einschraenkung": True,
        "verlust_arbeit": True,
        "soziale_isolation": True,
        "suizidalität": True,
        "begleitungen_gesamt": 6,
        "begleitungen_gerichte": 1,
        "begleitungen_polizei": 1,
        "begleitungen_rechtsanwaelte": 1,
        "begleitungen_aerzte": 1,
        "begleitungen_rechtsmedizin": 0,
        "begleitungen_jugendamt": 1,
        "begleitungen_sozialamt": 0,
        "begleitungen_jobcenter": 1,
        "begleitungen_beratungstellen": 0,
        "begleitungen_schutzeinrichtungen": 0,
        "begleitungen_schutzeinrichtungen_spezialisiert": 0,
        "begleitungen_interventionsstellen": 0,
        "verweise_gesamt": 5,
        "verweise_gerichte": 0,
        "verweise_polizei": 1,
        "verweise_rechtsanwaelte": 1,
        "verweise_aerzte": 1,
        "verweise_rechtsmedizin": 0,
        "verweise_jugendamt": 0,
        "verweise_sozialamt": 1,
        "verweise_jobcenter": 0,
        "verweise_beratungstellen": 1,
        "verweise_schutzeinrichtungen": 0,
        "verweise_schutzeinrichtungen_spezialisiert": 0,
        "verweise_interventionsstellen": 0,
        "quelle": "Selbstmeldung über Polizei",
        "dolmetsch_zeit": 120
    }
)

# Fall 4
DataSet.objects.create(
    data_record="Fall",
    version=1,
    values={
        "alias": "Chris P.",
        "rolle": "Betroffene:r",
        "alter": 55,
        "geschlechts_identitaet": "cis weiblich",
        "sexualitaet": "heterosexuell",
        "wohnort": "Sachsen",
        "staatsangehoerigkeit": "deutsch",
        "berufssituation": "berentet",
        "schwerbehinderung": True,
        "schwerbehinderung_form": "kognitiv",
        "schwerbehinderung_grad": "30",
        "beratungsstelle": "Stadt Leipzig",
        "anzahl_beratungen": 8,
        "depression": False,
        "angststoerung": False,
        "ptbs": False,
        "anderes": False,
        "burn_out": False,
        "schlafstoerung": False,
        "sucht": False,
        "kommunikationsschwierigkeiten": False,
        "vernachlaessigung_alltäglicher_dinge": False,
        "schmerzen": True,
        "laehmungen": True,
        "krankheit": True,
        "finanzielle_folgen": False,
        "arbeits_einschraenkung": False,
        "verlust_arbeit": False,
        "soziale_isolation": False,
        "suizidalität": False,
        "begleitungen_gesamt": 10,
        "begleitungen_gerichte": 2,
        "begleitungen_polizei": 3,
        "begleitungen_rechtsanwaelte": 2,
        "begleitungen_aerzte": 2,
        "begleitungen_rechtsmedizin": 1,
        "begleitungen_jugendamt": 0,
        "begleitungen_sozialamt": 0,
        "begleitungen_jobcenter": 0,
        "begleitungen_beratungstellen": 0,
        "begleitungen_schutzeinrichtungen": 0,
        "begleitungen_schutzeinrichtungen_spezialisiert": 0,
        "begleitungen_interventionsstellen": 0,
        "verweise_gesamt": 2,
        "verweise_gerichte": 1,
        "verweise_polizei": 0,
        "verweise_rechtsanwaelte": 1,
        "verweise_aerzte": 0,
        "verweise_rechtsmedizin": 0,
        "verweise_jugendamt": 0,
        "verweise_sozialamt": 0,
        "verweise_jobcenter": 0,
        "verweise_beratungstellen": 0,
        "verweise_schutzeinrichtungen": 0,
        "verweise_schutzeinrichtungen_spezialisiert": 0,
        "verweise_interventionsstellen": 0,
        "quelle": "Gesundheitswesen (Arzt/Ärztin)",
        "dolmetsch_zeit": 0
    }
)

# Fall 5
DataSet.objects.create(
    data_record="Fall",
    version=1,
    values={
        "alias": "Morgan T.",
        "rolle": "anonym",
        "alter": 33,
        "geschlechts_identitaet": "trans männlich",
        "sexualitaet": "schwul",
        "wohnort": "Sonstiges",
        "staatsangehoerigkeit": "syrisch",
        "berufssituation": "arbeitslos",
        "schwerbehinderung": False,
        "beratungsstelle": "Landkreis Leipzig",
        "anzahl_beratungen": 2,
        "depression": True,
        "angststoerung": False,
        "ptbs": True,
        "anderes": False,
        "burn_out": True,
        "schlafstoerung": False,
        "sucht": False,
        "kommunikationsschwierigkeiten": True,
        "vernachlaessigung_alltäglicher_dinge": True,
        "schmerzen": False,
        "laehmungen": False,
        "krankheit": False,
        "finanzielle_folgen": True,
        "arbeits_einschraenkung": False,
        "verlust_arbeit": True,
        "soziale_isolation": True,
        "suizidalität": False,
        "begleitungen_gesamt": 3,
        "begleitungen_gerichte": 0,
        "begleitungen_polizei": 0,
        "begleitungen_rechtsanwaelte": 0,
        "begleitungen_aerzte": 0,
        "begleitungen_rechtsmedizin": 0,
        "begleitungen_jugendamt": 0,
        "begleitungen_sozialamt": 1,
        "begleitungen_jobcenter": 1,
        "begleitungen_beratungstellen": 1,
        "begleitungen_schutzeinrichtungen": 0,
        "begleitungen_schutzeinrichtungen_spezialisiert": 0,
        "begleitungen_interventionsstellen": 0,
        "verweise_gesamt": 4,
        "verweise_gerichte": 0,
        "verweise_polizei": 0,
        "verweise_rechtsanwaelte": 0,
        "verweise_aerzte": 1,
        "verweise_rechtsmedizin": 0,
        "verweise_jugendamt": 0,
        "verweise_sozialamt": 1,
        "verweise_jobcenter": 1,
        "verweise_beratungstellen": 1,
        "verweise_schutzeinrichtungen": 0,
        "verweise_schutzeinrichtungen_spezialisiert": 0,
        "verweise_interventionsstellen": 0,
        "quelle": "Private Kontakte",
        "dolmetsch_zeit": 180
    }
)

print("5 Testfälle erfolgreich erstellt!")