# Generated by Django 5.2.8 on 2026-01-03 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wie', models.CharField(max_length=200)),
                ('datum', models.DateField(default=datetime.date.today)),
                ('ort', models.CharField(choices=[('S', 'Stadt Leipzig'), ('L', 'Landkreis Leipzig'), ('N', 'Landkreis Nordsachsen'), ('B', 'Sachsen'), ('A', 'Anderes')], max_length=1)),
                ('rolle', models.CharField(choices=[('F', 'Fachkraft'), ('A', 'Angehörige:r'), ('B', 'Betroffene:r'), ('U', 'anonym'), ('qB', 'queer Betroffene:r'), ('qF', 'queer Fachkraft'), ('qA', 'queer Angehörige:r'), ('qU', 'queer anonym'), ('FfB', 'Fachkraft für Betroffene:r'), ('AfB', 'Angehörige:r für Betroffene:r'), ('FfqB', 'Fachkraft für queere Betroffene:r'), ('AfqB', 'Angehörige:r für queere Betroffene:r')], max_length=4)),
                ('art', models.CharField(choices=[('MSH', 'medizinische Soforthilfe'), ('VSS', 'Vertrauliche Spurensicherung'), ('B', 'Beratungsbedarf'), ('BR', 'Beratungsbedarf zu Rechtlichem'), ('S', 'Sonstiges')], max_length=3)),
                ('termin', models.BooleanField()),
                ('termin_ort', models.CharField(choices=[('S', 'Stadt Leipzig'), ('L', 'Landkreis Leipzig'), ('N', 'Landkreis Nordsachsen')], max_length=1)),
                ('termin_datum', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Fall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('rolle', models.CharField(choices=[('B', 'Betroffene:r'), ('A', 'Angehörige:r'), ('F', 'Fachkraft')], max_length=1)),
                ('alter', models.IntegerField(blank=True)),
            ],
        ),
    ]
