# Generated by Django 5.2.8 on 2026-01-03 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anfrage',
            name='art',
        ),
        migrations.RemoveField(
            model_name='anfrage',
            name='datum',
        ),
        migrations.RemoveField(
            model_name='anfrage',
            name='ort',
        ),
        migrations.RemoveField(
            model_name='anfrage',
            name='rolle',
        ),
        migrations.RemoveField(
            model_name='anfrage',
            name='termin',
        ),
        migrations.RemoveField(
            model_name='anfrage',
            name='wie',
        ),
        migrations.AddField(
            model_name='anfrage',
            name='anfrage_art',
            field=models.CharField(blank=True, choices=[('M', 'medizinische Soforthilfe'), ('S', 'Vertrauliche Spurensicherung'), ('B', 'Beratungsbedarf'), ('R', 'Beratungsbedarf zu Rechtlichem'), ('X', 'Sonstiges')], max_length=1),
        ),
        migrations.AddField(
            model_name='anfrage',
            name='im_auftrag',
            field=models.BooleanField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anfrage',
            name='ist_queer',
            field=models.BooleanField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anfrage',
            name='mit_termin',
            field=models.BooleanField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anfrage',
            name='sende_art',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='anfrage',
            name='sende_datum',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='anfrage',
            name='sende_ort',
            field=models.CharField(blank=True, choices=[('S', 'Stadt Leipzig'), ('L', 'Landkreis Leipzig'), ('N', 'Landkreis Nordsachsen'), ('B', 'Sachsen'), ('X', 'Sonstiges')], max_length=1),
        ),
        migrations.AddField(
            model_name='anfrage',
            name='sender_rolle',
            field=models.CharField(blank=True, choices=[('B', 'Betroffene:r'), ('F', 'Fachkraft'), ('A', 'Angehörige:r'), ('U', 'anonym')], max_length=1),
        ),
        migrations.AddField(
            model_name='fall',
            name='berufssituation',
            field=models.CharField(blank=True, choices=[('L', 'arbeitslos'), ('S', 'studierend'), ('B', 'berufstätig'), ('R', 'berentet'), ('A', 'Azubi'), ('U', 'berufsunfähig')], max_length=1),
        ),
        migrations.AddField(
            model_name='fall',
            name='geschlecht',
            field=models.CharField(blank=True, choices=[('C', 'cis weiblich'), ('T', 'trans weiblich'), ('M', 'trans männlich'), ('N', 'trans nicht binär'), ('I', 'inter'), ('A', 'agender'), ('D', 'divers')], max_length=1),
        ),
        migrations.AddField(
            model_name='fall',
            name='notizen',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fall',
            name='schwerbehinderung',
            field=models.BooleanField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fall',
            name='schwerbehinderung_form',
            field=models.CharField(blank=True, choices=[('P', 'kognitiv'), ('K', 'körperlich')], max_length=1),
        ),
        migrations.AddField(
            model_name='fall',
            name='schwerbehinderung_grad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fall',
            name='sexualitaet',
            field=models.CharField(blank=True, choices=[('L', 'lesbisch'), ('S', 'schwul'), ('B', 'bisexuell'), ('A', 'asexuell'), ('H', 'heterosexuell')], max_length=1),
        ),
        migrations.AddField(
            model_name='fall',
            name='staatsangehoerigkeit',
            field=models.CharField(blank=True, choices=[('S', 'Stadt Leipzig'), ('L', 'Landkreis Leipzig'), ('N', 'Landkreis Nordsachsen'), ('B', 'Sachsen'), ('X', 'Sonstiges')], max_length=1),
        ),
        migrations.AddField(
            model_name='fall',
            name='wohnort',
            field=models.CharField(blank=True, choices=[('S', 'Stadt Leipzig'), ('L', 'Landkreis Leipzig'), ('N', 'Landkreis Nordsachsen'), ('B', 'Sachsen'), ('X', 'Sonstiges')], max_length=1),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='termin_datum',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='termin_ort',
            field=models.CharField(blank=True, choices=[('S', 'Stadt Leipzig'), ('L', 'Landkreis Leipzig'), ('N', 'Landkreis Nordsachsen')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fall',
            name='alias',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fall',
            name='rolle',
            field=models.CharField(blank=True, choices=[('B', 'Betroffene:r'), ('F', 'Fachkraft'), ('A', 'Angehörige:r'), ('U', 'anonym')], max_length=1),
        ),
    ]
