# Generated by Django 5.2.8 on 2026-01-03 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_anfrage_art_remove_anfrage_datum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anfrage',
            name='anfrage_art',
            field=models.CharField(choices=[('M', 'medizinische Soforthilfe'), ('S', 'Vertrauliche Spurensicherung'), ('B', 'Beratungsbedarf'), ('R', 'Beratungsbedarf zu Rechtlichem'), ('X', 'Sonstiges')], max_length=1),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='im_auftrag',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='ist_queer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='mit_termin',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='sende_art',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='sende_datum',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='sende_ort',
            field=models.CharField(choices=[('S', 'Stadt Leipzig'), ('L', 'Landkreis Leipzig'), ('N', 'Landkreis Nordsachsen'), ('B', 'Sachsen'), ('X', 'Sonstiges')], max_length=1),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='sender_rolle',
            field=models.CharField(choices=[('B', 'Betroffene:r'), ('F', 'Fachkraft'), ('A', 'Angehörige:r'), ('U', 'anonym')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fall',
            name='alias',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fall',
            name='notizen',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fall',
            name='rolle',
            field=models.CharField(choices=[('B', 'Betroffene:r'), ('F', 'Fachkraft'), ('A', 'Angehörige:r'), ('U', 'anonym')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fall',
            name='schwerbehinderung',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='schwerbehinderung_form',
            field=models.CharField(choices=[('P', 'kognitiv'), ('K', 'körperlich')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fall',
            name='schwerbehinderung_grad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fall',
            name='staatsangehoerigkeit',
            field=models.CharField(choices=[('S', 'Stadt Leipzig'), ('L', 'Landkreis Leipzig'), ('N', 'Landkreis Nordsachsen'), ('B', 'Sachsen'), ('X', 'Sonstiges')], max_length=1),
        ),
    ]
