# Generated by Django 5.2.8 on 2026-01-03 19:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_anfrage_anfrage_art_alter_anfrage_im_auftrag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Begleitungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GewaltFolgen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depression', models.BooleanField(default=False)),
                ('angststoerung', models.BooleanField(default=False)),
                ('ptbs', models.BooleanField(default=False)),
                ('anderes', models.BooleanField(default=False)),
                ('burn_out', models.BooleanField(default=False)),
                ('schlafstoerung', models.BooleanField(default=False)),
                ('sucht', models.BooleanField(default=False)),
                ('kommunikationsschwierigkeiten', models.BooleanField(default=False)),
                ('vernachlaessigung_alltäglicher_dinge', models.BooleanField(default=False)),
                ('schmerzen', models.BooleanField(default=False)),
                ('laehmungen', models.BooleanField(default=False)),
                ('krankheit', models.BooleanField(default=False)),
                ('dauerhafte_beeintraechtigung', models.CharField(blank=True, max_length=50)),
                ('finanzielle_folgen', models.BooleanField(default=False)),
                ('arbeits_einschraenkung', models.BooleanField(default=False)),
                ('verlust_arbeit', models.BooleanField(default=False)),
                ('soziale_isolation', models.BooleanField(default=False)),
                ('suizidalität', models.BooleanField(default=False)),
                ('sonstiges', models.BooleanField(default=False)),
                ('notizen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gewalttat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alter', models.IntegerField(blank=True)),
                ('zeitraum', models.IntegerField(blank=True)),
                ('anzahl_vorfaelle', models.IntegerField(blank=True)),
                ('anzahl_taeter', models.IntegerField(blank=True)),
                ('tatort', models.CharField(choices=[('S', 'Stadt Leipzig'), ('L', 'Landkreis Leipzig'), ('N', 'Landkreis Nordsachsen'), ('B', 'Sachsen'), ('D', 'Deutschland'), ('A', 'Ausland'), ('F', 'auf der Flucht'), ('H', 'im Herkunftsland')], max_length=1)),
                ('anzeige', models.CharField(choices=[('J', 'Ja'), ('N', 'Nein'), ('U', 'noch nicht entschieden')], max_length=1)),
                ('med_versorgung', models.BooleanField(blank=True)),
                ('betroffene_kinder', models.IntegerField(blank=True)),
                ('betroffene_kinder_direkt', models.IntegerField(blank=True)),
                ('notizen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Verweise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anzahl', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='fall',
            name='dolmetsch_sprache',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='fall',
            name='dolmetsch_zeit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fall',
            name='quelle',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Beratungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beratungsstelle', models.CharField(choices=[('S', 'Stadt Leipzig'), ('L', 'Landkreis Leipzig'), ('N', 'Landkreis Nordsachsen')], max_length=1)),
                ('anzahl_beratungen', models.IntegerField(default=0)),
                ('fall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.fall')),
            ],
        ),
        migrations.CreateModel(
            name='Beratung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=datetime.date.today)),
                ('art', models.CharField(choices=[('P', 'persönlich'), ('V', 'video'), ('T', 'telefon'), ('A', 'aufsuchend'), ('S', 'schriftlich')], max_length=1)),
                ('ort', models.CharField(choices=[('S', 'Stadt Leipzig'), ('L', 'Landkreis Leipzig'), ('N', 'Landkreis Nordsachsen')], max_length=1)),
                ('notizen', models.CharField(max_length=50)),
                ('fall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='database.beratungen')),
            ],
        ),
        migrations.CreateModel(
            name='GewaltArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexueller_belaestigung_oeffentlich', models.BooleanField(default=False)),
                ('sexueller_belaestigung_arbeit', models.BooleanField(default=False)),
                ('sexueller_belaestigung_privat', models.BooleanField(default=False)),
                ('vergewaltigung', models.BooleanField(default=False)),
                ('versuchte_vergewaltigung', models.BooleanField(default=False)),
                ('sexueller_missbrauch', models.BooleanField(default=False)),
                ('sexueller_missbrauch_kindheit', models.BooleanField(default=False)),
                ('sexuelle_noetigung', models.BooleanField(default=False)),
                ('rituelle_gewalt', models.BooleanField(default=False)),
                ('zwangsprostitution', models.BooleanField(default=False)),
                ('sexuelle_ausbeutung', models.BooleanField(default=False)),
                ('upskirting', models.BooleanField(default=False)),
                ('catcalling', models.BooleanField(default=False)),
                ('digitale_sexuelle_gewalt', models.BooleanField(default=False)),
                ('spiking', models.BooleanField(default=False)),
                ('weitere', models.CharField(max_length=200)),
                ('tat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gewalttat')),
            ],
        ),
        migrations.CreateModel(
            name='Taeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geschlecht', models.CharField(max_length=50)),
                ('beziehung', models.CharField(choices=[('U', 'Unbekannte:r'), ('B', 'Bekannte:r'), ('P', 'Partner:in'), ('A', 'Partner:in ehemalig'), ('E', 'Ehepartner:in oder eingetragene:r Lebenspartner:in'), ('F', 'andere:r Familienangehörige:r'), ('X', 'Sonstige:r')], max_length=1)),
                ('tat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gewalttat')),
            ],
        ),
    ]
