# Generated by Django 5.2.8 on 2026-01-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_delete_begleitungen_remove_beratungen_fall_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gewalttat',
            old_name='sexueller_belaestigung_arbeit',
            new_name='sexuelle_belaestigung_arbeit',
        ),
        migrations.RenameField(
            model_name='gewalttat',
            old_name='sexueller_belaestigung_oeffentlich',
            new_name='sexuelle_belaestigung_oeffentlich',
        ),
        migrations.RenameField(
            model_name='gewalttat',
            old_name='sexueller_belaestigung_privat',
            new_name='sexuelle_belaestigung_privat',
        ),
    ]
