# Generated by Django 5.2.8 on 2026-01-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_sexueller_belaestigung_arbeit_gewalttat_sexuelle_belaestigung_arbeit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beratung',
            name='fall',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='fall',
        ),
        migrations.RemoveField(
            model_name='taeter',
            name='tat',
        ),
        migrations.AddField(
            model_name='fall',
            name='beratungen',
            field=models.ManyToManyField(to='database.beratung'),
        ),
        migrations.AddField(
            model_name='fall',
            name='gewalttaten',
            field=models.ManyToManyField(to='database.gewalttat'),
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='taeter',
            field=models.ManyToManyField(to='database.taeter'),
        ),
    ]
