# Generated by Django 5.2.8 on 2026-01-06 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_beratung_fall_remove_gewalttat_fall_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beratung',
            old_name='ort',
            new_name='stelle',
        ),
        migrations.RemoveField(
            model_name='fall',
            name='beratungen',
        ),
        migrations.RemoveField(
            model_name='fall',
            name='gewalttaten',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='taeter',
        ),
        migrations.AddField(
            model_name='beratung',
            name='fall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.fall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='fall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.fall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taeter',
            name='gewalttat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='database.gewalttat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beratung',
            name='notizen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fall',
            name='begleitungen_sonstige',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fall',
            name='notizen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fall',
            name='notizen_folgen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fall',
            name='schwerbehinderung_form',
            field=models.CharField(blank=True, choices=[('P', 'kognitiv'), ('K', 'körperlich')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fall',
            name='schwerbehinderung_grad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fall',
            name='verweise_sonstige',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fall',
            name='weiteres',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gewalttat',
            name='notizen',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
