# Generated by Django 5.2.8 on 2026-01-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_ort_beratung_stelle_remove_fall_beratungen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beratung',
            old_name='stelle',
            new_name='ort',
        ),
        migrations.RemoveField(
            model_name='beratung',
            name='fall',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='fall',
        ),
        migrations.RemoveField(
            model_name='taeter',
            name='gewalttat',
        ),
        migrations.AddField(
            model_name='fall',
            name='beratungen',
            field=models.ManyToManyField(blank=True, to='database.beratung'),
        ),
        migrations.AddField(
            model_name='fall',
            name='gewalttaten',
            field=models.ManyToManyField(blank=True, to='database.gewalttat'),
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='taeter',
            field=models.ManyToManyField(blank=True, to='database.taeter'),
        ),
        migrations.AlterField(
            model_name='beratung',
            name='notizen',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='gewalttat',
            name='notizen',
            field=models.CharField(max_length=200),
        ),
    ]
