# Generated by Django 5.2.8 on 2026-01-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_rename_stelle_beratung_ort_remove_beratung_fall_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beratung',
            old_name='ort',
            new_name='stelle',
        ),
        migrations.RemoveField(
            model_name='fall',
            name='beratungen',
        ),
        migrations.RemoveField(
            model_name='fall',
            name='gewalttaten',
        ),
        migrations.RemoveField(
            model_name='gewalttat',
            name='taeter',
        ),
        migrations.AddField(
            model_name='beratung',
            name='fall',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.fall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gewalttat',
            name='fall',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.fall'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taeter',
            name='gewalttat',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='database.gewalttat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beratung',
            name='notizen',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gewalttat',
            name='notizen',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
