# Generated by Django 5.2.8 on 2026-01-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_rename_ort_beratung_stelle_remove_fall_beratungen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gewalttat',
            name='weitere',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
