# Generated by Django 5.2.8 on 2026-01-07 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='DataRecord',
        ),
    ]
