# Generated by Django 5.2.8 on 2026-01-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_rename_type_datarecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anfrage',
            name='anfrage_art',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='sende_art',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='sende_datum',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='sende_ort',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='sender_rolle',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='anfrage',
            name='termin_ort',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='beratung',
            name='stelle',
            field=models.CharField(choices=[], max_length=1),
        ),
        migrations.AlterField(
            model_name='fall',
            name='beratungsstelle',
            field=models.CharField(choices=[], max_length=1),
        ),
        migrations.AlterField(
            model_name='fall',
            name='rolle',
            field=models.CharField(choices=[], max_length=1),
        ),
        migrations.AlterField(
            model_name='fall',
            name='wohnort',
            field=models.CharField(blank=True, choices=[], max_length=1),
        ),
    ]
