# Generated by Django 5.2.8 on 2026-01-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_anfrage_anfrage_art_alter_anfrage_sende_art_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fall',
            name='geschlecht',
        ),
        migrations.AddField(
            model_name='fall',
            name='geschlechts_identitaet',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='fall',
            name='andere_quelle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fall',
            name='anderes',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='angststoerung',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='arbeits_einschraenkung',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='beratungsstelle',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='fall',
            name='berufssituation',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='fall',
            name='burn_out',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='dauerhafte_beeintraechtigung',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fall',
            name='depression',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='dolmetsch_sprache',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fall',
            name='finanzielle_folgen',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='kommunikationsschwierigkeiten',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='krankheit',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='laehmungen',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='ptbs',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='quelle',
            field=models.CharField(blank=True, choices=[], max_length=1),
        ),
        migrations.AlterField(
            model_name='fall',
            name='rolle',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='fall',
            name='schlafstoerung',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='schmerzen',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='schwerbehinderung_form',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='fall',
            name='schwerbehinderung_grad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fall',
            name='sexualitaet',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='fall',
            name='soziale_isolation',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='staatsangehoerigkeit',
            field=models.CharField(blank=True, default='Deutschland', max_length=100),
        ),
        migrations.AlterField(
            model_name='fall',
            name='sucht',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='suizidalität',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='verlust_arbeit',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='vernachlaessigung_alltäglicher_dinge',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='fall',
            name='wohnort',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
    ]
