# Generated by Django 5.2.8 on 2026-01-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_remove_fall_geschlecht_fall_geschlechts_identitaet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beratung',
            name='art',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='beratung',
            name='stelle',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='gewalttat',
            name='anzeige',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='gewalttat',
            name='tatort',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='taeter',
            name='beziehung',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='taeter',
            name='geschlecht',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
