# Generated by Django 5.2.8 on 2026-01-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_beratung_art_alter_beratung_stelle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarecord',
            name='version',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
