# Generated by Django 5.2.8 on 2026-02-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_case_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
